### ISSUE TITLE
How to perform inductive learning on PPI?

### ISSUE THREAD

**Issue by Jhy1993** [danielegrattarola/keras-gat#15]
I feel confused about inductive learning on PPI.
How to utilize the trained model to get the node embedding on the unseen graph?
Thanks a lot in advance for your help!

**Comment by HwangWJ** [comment]
Hello, thank you so very very much for the keras gat code! 
I just finished understanding your code and the authors' paper.

I have a similar question actually about the inductive learning part of the work.

In this paper the authors say gat can do inductive learning(PPI), does this mean that 
if the gat is trained with graphs with certain topology A1, A2, ... An  then this gat should be able to do prediction on arbitrary unseen topologies  A1', A2' , A3'  , unseen during training?  

~~And so that I can  model.fit ( X, B )  on many Bs  and do model.predict( X' ,B' ) ?   
am i getting it right?

**Comment by danielegrattarola** [comment]
I've never worked with GAT in the inductive setting, but I guess it should be easy to implement. 
You'd need to either: 

1. Train the model on the disjoint union of your graphs
2. Stack your graphs in batches, and adapt the code to handle the additional dimension. 

Anyway, yes, the process you're describing is inductive learning.
