### ISSUE TITLE
How to train the model through minibatch of samples

### ISSUE THREAD

**Issue by qzshadow** [danielegrattarola/keras-gat#16]
Hi Daniele, 
Thanks for your precise code, I have a trouble running your code on a huge graph (with 3 million of vertexes and 40 million of edges), It was mainly caused by memory error, so I try to feed the model by mini batches of samples.
What I have tried is to modify parameter "batch_size" in the following places:
1. Add a parameter called `bs=128` as batch_size
2. Modify `batch_size=N` to `batch_size=bs` in line 59, 67, 76
When I run `python gat.py`, I got the error message
```
Incompatible shapes: [128,128] vs. [128,2708]
```
Could you give some advice how to modify the code to minibatch training way?

**Comment by danielegrattarola** [comment]
One of the current problems with graph convolutions is that you need to have the whole graph in memory. Think it like this: if you take 128 nodes at a time, then convolutions can only work if those 128 node are only neighbours with each other.
Take this toy example:
```
adj = [[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]  # adjacency matrix, shape N x N, fully connected graph
nf = [[1], 
      [2],
      [3]]  # node features, shape N x F
```
If you apply graph convolutions to `nf`, the output associated to the first node will be:
```
nf_out[0] = adj[0, 0] * w_0 * nf[0] + w_adj[0, 1] * w_1 * nf[1] + w_adj[0, 2] * w_2 * nf[2] = 
          = w_0 * nf[0] + w_1 * nf[1] + w_2 * nf[2] = w_0 * 1 + w_1 * 2 + w_2 * 3
```
where `w_i` are the weights of the convolution filter (I'm ignoring the attention part). 
Now imagine if you took a batch of nodes instead of the whole graph, say with `batch_size = 2`: at the first update, you'd have access to `nf[0]` and `nf[1]`, but `nf[2]` would not be in memory. 
That's why batching doesn't work with this implementation. Your best bet is to use sparse matrices, and, if that fails, to re-implement everything with a different logic. 

Hope this helps.

**Comment by qzshadow** [comment]
Got it, thanks. BWT, when you mention sparse matrices, a better way to add self-loop for adjacency matrix `A` is through
```
eye_data = np.ones((A.shape[0],),dtype=int)
eye_row = np.array(xrange(A.shape[0]),dtype=int)
A = A + csr_matrix((eye_data,(eye_row, eye_row)),dtype=int)  # Add self-loops
```
Because your in implementation, 
```
A = A + np.eye(A.shape[0])  # Add self-loops
```
will transform the sparse matrix A to a dense matrix again.

**Comment by danielegrattarola** [comment]
Yes, I didn't really implement the layer with sparse matrices in mind. 
If you do implement it, it would be nice to merge it in this repo :)
